version: '3.7'

networks:
  task_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '10.101.0.0/16'
services:
  db:
    image: mysql
    hostname: db
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - task_net
    ports:
      - '127.0.0.1:3306:3306'
    restart: "no"
    command: --max-allowed-packet=134217728
    environment:
      MYSQL_ROOT_PASSWORD: root
  #  crud:
  #    image: tomcat:9.0.65-jdk17-temurin-jammy
  #    hostname: crud
  #    restart: no
  #    networks:
  #      - task_net
  #    ports:
  #      - '127.0.0.1:8080:8080'
  #    depends_on:
  #      - db
  #      - app
  #    volumes:
  #      - ~/tomcat/conf:/usr/local/tomcat/conf
  #      - ~/tomcat/webapps:/usr/local/tomcat/webapps
  app:
    image: nginx
    hostname: app
    restart: "no"
    volumes:
      - ~/tasks-frontend:/usr/share/nginx/html/
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - '127.0.0.1:80:80'
  mailcatcher:
    image: schickling/mailcatcher:latest
    hostname: mailcatcher
    networks:
      task_net:
        aliases:
          - mail.synevo.pl
    ports:
      - '127.0.0.1:1080:1080'
      - '127.0.0.1:1025:1025'
#  revproxy:
#    image: nginx:stable
#    volumes:
#      - ./revproxy.conf:/etc/nginx/conf.d/default.conf:ro
##      - ./dev.3s.pl.key:/etc/nginx/dev.3s.pl.key:ro
##      - ./dev.3s.pl.chain.crt:/etc/nginx/dev.3s.pl.crt:ro
#    ports:
#      - '127.0.0.1:80:80'
#      - '127.0.0.1:443:443'
#    depends_on:
#      - crud
#      - app
#    networks:
#      task_net:
#        aliases:
#          - crud.tasks.com
#          - app.tasks.com
