spring:
  datasource:
    url: "jdbc:mysql://db:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=false&allowPublicKeyRetrieval=true"
    username: tasks
    password: crud_password
  jpa:
    database:
      mysql
    show-sql: true
    hibernate:
      ddl-auto: update