spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=false&allowPublicKeyRetrieval=true"
  mail:
    username: 32f79161622309
    password: 28ece251c3a84e
