spring:
  datasource:
    url: "jdbc:mysql://db:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=false&allowPublicKeyRetrieval=true"
    username: tasks
    password: crud_password
  jpa:
    database:
      mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  frontend:
    url: http://localhost

trello:
  api:
    endpoint:
      prod: https://api.trello.com/1
  app:
    key: c563461cf4951691eae46dabc1c16337
    token: ddb5eacc4e1da1c2902a6ce590d031a4b0eea8186bb7741bcaf9262f6f86a58d
    username: shinzu__

admin:
  mail: oskar.sek94@gmail.com

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: Tasks Application
    description: Application has been created on Kodilla course!
    version: 1.0.0
    owner:
      name: Johon
      surname: Doe
    administrator:
      email: john.doe@test.com
      address:
        street: Super Cool Street
        number: 42
  company:
    name: TaskCrudAppCreator
    goal: Our goal is to make the world a better place!
    email: task@crud.com
    phone: 744489230