spring:
  datasource:
    url: "jdbc:mysql://db:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=false&allowPublicKeyRetrieval=true"
    username: tasks
    password: crud_password
  jpa:
    database:
      mysql
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  frontend:
    url: http://localhost

trello:
  api:
    endpoint:
      prod: https://api.trello.com/1
  app:
    key: c563461cf4951691eae46dabc1c16337
    token: ddb5eacc4e1da1c2902a6ce590d031a4b0eea8186bb7741bcaf9262f6f86a58d
    username: shinzu__